name: Show Release Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  show_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show RELEASE_VERSION
        run: echo "RELEASE_VERSION = $RELEASE_VERSION"
